### ISSUE TITLE
bugs?

### ISSUE THREAD

**Issue by rumcode** [Amay22/NASDAQ-ITCH-5.0-Parser#3]
Nice improvement!, but there seems to be a bug. There is fArray, but no fArray1 defined in parseDS.java! see below (did you copy the code in right to github?
    public void buildFormats() {
        fMap = new HashMap<>();
        ArrayList<Object> fArray = (ArrayList<Object>) yMap.get("formats");

```
    fArray.stream().map((fArray1) -> (Map<Object, Object>) fArray1).forEach((tempMap) -> {
        fMap.put(tempMap.keySet().toArray()[0], tempMap.values().toArray()[0]);
    });
}
```

2) you were asking about the dataset I used: This time I used: 02022015.NASDAQ_ITCH50.gz

3) The specs say for prices 4 decimals. But the output seems to show only 2. I'm not sure that most of the data is only two decimals, but can the code handle 4? Periodically makers will jump in front of another buy posting a price such as 50.0199 instead of 50.0200.

4) This is not a problem with your code but with the ITCH specs. If you look at the specs for message type "P" and "Q" you will see that one specifies shares as integer 4 and the other as integer 8.  In the yaml file, shares is only defined once.  So I'm guessing that the code might not report the case of integer 8 correctly. Its worth while checking into.

**Comment by Amay22** [comment]
@rumcode Good analysis.

1.) The `fArray1` is a mapping of the `fArray Arraylist`. It is the new Java syntax. Now the `fArray1` element is being used in the syntax of a `foreach` loop whose each element is being mapped to `tempMap`.

I believe if you look at the code again you'll see it. I didn't know all this existed myself until I started updating my knowledge on Java 8. 

2.) I was using the Saturday data-set because it was small. I have a monster Alienware but it starts burning up and my Mac completely dissolves. I thought all this was testing data and wasn't real but based upon your previous issue I guess this data is real and check it on Yahoo Finance. I guess I'll just suck up and start splitting the files and even after that I have start learning Hadoop.

3.) The code can handle 4 and 8 decimal places because the code parses any float to double and and then divides by 10000. The code  for 4 decimal places can be found here : 
https://github.com/Amay22/NASDAQ-ITCH-5.0-Parser/blob/master/src/Parsers.java#L30-L34

and for  8 decimal places it is here:
https://github.com/Amay22/NASDAQ-ITCH-5.0-Parser/blob/master/src/Parsers.java#L75

4.) This is the part which makes me wonder. How did you see that? It's like you were looking for specifically. I'll fix it.

**Comment by rumcode** [comment]
Regarding(1) perhaps I was using and older java compiler so it complained. All of my stuff is in Eclipse/Helios and previous version of java. 

Regarding data. Perhaps you can just  hop over to Bobst  and get the larger files and put it on a USB stick. I'm guessing that the data you are using is not really good for testing because it may miss several types of data such as IPO messages, trading halts or limit down/limit up cases.
It would have been much better for nasdaq to provide a dataset that has all the messages combinations  in it for testing purposes. This would in fact be less than 1k. 

Regarding (3) and (4). ok. if it works then it works, but I thought I should ask. 

In general most of the mistakes I found in your stuff was by gut feel. i.e. "nah... that does not seem right". It also comes from working with the data from another source which was in character format not binary so I could read the raw data into a text editor. (See www.tradingphysics.com or lobsterdata.com for data.) Both of these sources suffer from the fact they are not using itch 5.0 data and leave out important things such as order imbalance messages. Tradingphysics data does not have nanoseconds (it has milliseconds). so when one calculates the difference between the time the order entered to when it was deleted, you get 0 instead of say 500 nanoseconds.

 In regards to (4), I was passing some argument parameters and the compiler complained about mixing integer and long. So that was purely by accident.

**Comment by Amay22** [comment]
@rumcode Bobst ? USB ?

I added a new pararmeter for shares in "Q" cross trade messages and I guess that takes care of this issue. Is there anything else left ?
https://github.com/Amay22/NASDAQ-ITCH-5.0-Parser/blob/master/itch5.yaml#L9
https://github.com/Amay22/NASDAQ-ITCH-5.0-Parser/blob/master/itch5.yaml#L246

Please close the issue after you review.
Thanks for all that. I was never gonna look back on it.

**Comment by rumcode** [comment]
If you fixed it, then I'll close the comment. If there's a problem I will let you know.  Sometimes there is a ripple effect that is not easily noticed.

Bobst?...NYU's library at Washington Square Park.

**Comment by Shamim1977** [comment]
I was trying it with the following sample file-
http://optionsdata.baruch.cuny.edu/data1/delivery/nasdaq/S20180501-v50_sample.txt
and I am calling parser class from a JFrame, it parses 2 records and faces an out of index issue-

[S, 0, 0, 10949877220447, O]
[R, 1, 0, 14337433606119, A, , N, 536870912, d, N, CZ, , P, N, , 1, 1308622848, ]
Exception in thread "Thread-2" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at nasdaqitchparser.Parsers.messageIn(Parsers.java:45)
	at nasdaqitchparser.Parse.parse(Parse.java:65)

Can u please suggest what to do?
